name: "pagely-deploy"
on:
  push:
jobs:
  deploy:
    name: Deploy to Pagely
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Run deploy
        uses: godaddy-wordpress/pagely-deploy-action@v1
        with:
          PAGELY_DEPLOY_DEST: "/httpdocs/wp-content/plugins"
          PAGELY_INTEGRATION_SECRET: ${{secrets.PAGELY_INTEGRATION_SECRET}}
          PAGELY_INTEGRATION_ID: "W3KsbyFqP8uHUsqLKfXJ34"
          PAGELY_APP_ID: "42328"
          PAGELY_WORKING_DIR: ${{github.workspace}}
